# problem2.py

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.




if __name__ == '__main__':
    MAX_NUM = 4_000_000

    n1, n2 = 1,2
    sum_total = 2

    while n1 < MAX_NUM and n2 < MAX_NUM:
        new_fib = n1 + n2

        if new_fib % 2 == 0:
            sum_total += new_fib
        n1, n2 = n2, new_fib

    print(sum_total)

